variable "cidr_vpc" {}
variable "cidr_public1" {}
variable "cidr_public2" {}
variable "cidr_private1" {}
variable "cidr_private2" {}
variable "cidr_internet_gateway" {}
variable "cidr_nat_gateway" {}
variable "az1" {}
variable "az2" {}